import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext';
import Footer from "./components/Footer";
import Header from "./components/Header";
import { Toaster } from "@/components/ui/sonner"
import AdminHeader from "./components/AdminHeader";
import AdminFooter from "./components/AdminFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, layoutType }) {
  const isAdminLayout = layoutType === 'admin';
  return (
    <html lang="en">
      <body >
      <AuthProvider>
          {isAdminLayout ? <AdminHeader /> : <Header />}
          {children}
          {isAdminLayout ? <AdminFooter /> : <Footer />}
        </AuthProvider>
        <Toaster />
        </body>
    </html>
  );
}
